export enum ErrorEnum {
    ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
    ROOM_IS_FULL = 'ROOM_IS_FULL',
    INVALID_MOVE = 'INVALID_MOVE',
    NOT_YOUR_TURN = 'NOT_YOUR_TURN',
    GAME_NOT_RUNNNING = 'GAME_NOT_RUNNNING',
    PLAYER_ALREADY_CONNECTED = "PLAYER_ALREADY_CONNECTED"
}
