export enum RoomStatus {
    WAITING_FOR_OTHER_PLAYER = 'WAITING_FOR_OTHER_PLAYER',
    RUNNING = 'RUNNING',
    FINISHED = 'FINISHED',
    RESTARTING = 'RESTARTING',
    RESTART_VOTE = 'RESTART_VOTE'
}